name: 'Process reminders'

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reminder:
    permissions:
      issues: write  # for agrc/reminder-action to set reminders on issues
      pull-requests: write  # for agrc/reminder-action to set reminders on PRs
    runs-on: ubuntu-latest

    steps:
      - name: check reminders and notify
        uses: agrc/reminder-action@a0c856cdcf01fa596ba315c8e94bd46d83dc9de3 # v1.0.13
